added eth0 and changemac scripts

diff --git a/edison-image-edison-ext4/etc/network/if-pre-up.d/change-mac b/edison-image-edison-ext4/etc/network/if-pre-up.d/change-mac
--- a/edison-image-edison-ext4/etc/network/if-pre-up.d/change-mac
+++ b/edison-image-edison-ext4/etc/network/if-pre-up.d/change-mac
@@ -1,6 +1,11 @@
 #!/bin/bash
-# Set the MAC address of eth0.  This script is intended to be placed
-# in /etc/network/if-pre-up.d/
+# Set the MAC address of eth0, the Edison-Ethernet block. This script
+# is intended to be placed in /etc/network/if-pre-up.d/ with +x perm.
+
+MAC_FILE="/factory/mac"
+GREEN='\033[0;32m'
+RED='\033[0;31m'
+NC='\033[0m'
 
 # This will set eth0 while the system is working on lo
 if [ ! "$IFACE" == "lo" ];
@@ -8,17 +13,20 @@ then
     exit 0 
 fi
 
-OUI="00:1e:c0" #MICROCHIP OUI
-FOURTH=$(openssl rand -hex 1)
-FIFTH=$(openssl rand -hex 1)
-SIXTH=$(openssl rand -hex 1)
-
-ETH0="$OUI:$FOURTH:$FIFTH:$SIXTH"
-
-# Only do the work if eth0 is an interface
+# Only do the work if eth0 is an interface and the MAC_FILE exists
 ifconfig eth0 > /dev/null
-if [[ $? -eq 0 ]];
+if [[ $? -eq 0 && -f $MAC_FILE ]];
 then
-    echo "Setting eth0 MAC to $ETH0"
-    macchanger -m $ETH0 eth0 > /dev/null
+   ETH0=$(cat $MAC_FILE)
+
+   if [[ "$ETH0" =~ ^([0-9A-Fa-f]{2}[:-]){5}([0-9a-fA-F]{2})$ ]]; then
+      echo
+      echo -e "[${GREEN} ok ${NC}] Setting eth0 MAC to $ETH0"
+      macchanger -m $ETH0 eth0 > /dev/null
+   else
+      DEF_ETH0=$(ifconfig eth0 | grep -o -E '([[:xdigit:]]{1,2}:){5}[[:xdigit:]]{1,2}')
+      echo
+      echo -e "[${RED}fail${NC}] Invalid MAC address: $ETH0 [Try using the changemac command]"
+      echo "       Using default MAC for eth0: $DEF_ETH0"
+   fi
 fi
